#
# https://gitlab.cylab.be/cylab/monitoring
# docker-compose.yaml
#

services:
  web:
    image: gitlab.cylab.be:8081/cylab/monitoring:latest
    depends_on:
      - redis
      - mysql
    ports:
      - "80"
    volumes:
      - web:/var/www/html/storage
    restart: "unless-stopped"
    environment:
      WAIT_HOSTS: mysql:3306
    env_file: stack.env
    labels:
      - traefik.http.routers.monitoring.rule=Host(`monitoring.cylab.be`)
      - traefik.http.routers.monitoring.tls=true
      - traefik.http.routers.monitoring.tls.certresolver=letsencrypt

  scheduler:
    image: gitlab.cylab.be:8081/cylab/monitoring:latest
    depends_on:
      - web
    volumes:
      - web:/var/www/html/storage
    restart: "unless-stopped"
    environment:
      WAIT_HOSTS: web:80
    env_file: stack.env
    command: /scheduler.sh

  queue:
    image: gitlab.cylab.be:8081/cylab/monitoring:latest
    deploy:
      replicas: 4
    depends_on:
      - web
    volumes:
      - web:/var/www/html/storage
    command: /queue.sh
    env_file: stack.env
    restart: "unless-stopped"
    environment:
      WAIT_HOSTS: web:80

  redis:
    image: redis:4-alpine
    volumes:
      - redis:/data
    restart: "unless-stopped"

  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    restart: "unless-stopped"

volumes:
  web:
  mysql:
  redis: